<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [2]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
greeting("Super Man")

'Hello Super Man!'

In [3]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()
basic_stats([1, 2, 3, 4, 5])

(1, 5, 3.0)

### 1.2 Named functions that don’t return

In [ ]:
#A function does not have to return anything. e.g.print

### 1.3 Anonymous functions

In [5]:
my_short_function = lambda name: f"Hello {name}!"
my_short_function("Super Man")

'Hello Super Man!'

In [6]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         # Sort by comparing the default key 
                                        # (i.e. the 1st element) 
    

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [ ]:
sorted(numbers, key=lambda x: x[1])     # Sort by comparing a custom key
                                        # that uses the 2nd element

In [ ]:
sorted(numbers, key=lambda x: sum(x))   # Sort by comparing a custom key
                                        # that uses the sum of the elements

### 1.4 Optional arguments

In [7]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
greeting()

'Hello no one!'

In [ ]:
print('I', 'am', 'Batman!')                 # Just for comparison
#> I am Batman!
print('I', 'am', 'Batman!', sep='---')  
#> I---am---Batman!

## 2 The importance of functions?

### 2.1 An argument for functions

### 2.2 A word of caution

## Exercise 1 :  Do you know why?

In [ ]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'

The use of indentaton?

## Exercise 2 :  Calculator functions

In [11]:
import numpy as np

def add(x,y):
    x=np.array(x) 
    y=np.array(y)
    return x+y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

add(x,y)
    

array([100, 100, 100, 100, 100])

In [12]:
import numpy as np

def substract(x,y):
    x=np.array(x) 
    y=np.array(y)
    return x-y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

substract(x,y)
    

array([-28, -32, -12,  52, -46])

In [13]:
import numpy as np

def multiply(x,y):
    x=np.array(x) 
    y=np.array(y)
    return x*y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

multiply(x,y)
    

array([2304, 2244, 2464, 1824, 1971])

In [1]:
import numpy as np

def divide(x,y):
    x=np.array(x) 
    y=np.array(y)
    if y.all()!=0:
        return x/y
    else:
        exit()

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 6, 56, 24, 73])

divide(x,y)
    

In [1]:
import numpy as np

def divide(x,y):
    x=np.array(x) 
    y=np.array(y)
    if np.all(y!=0):
        return x/y
    else:
        exit()

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 0, 56, 24, 73])

divide(x,y)
    

In [6]:
import numpy as np

def divide(x,y):
    x=np.array(x) 
    y=np.array(y)
    if np.any(y==0):  #syntax
        exit()
    else:
        return x/y         
        

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 0, 56, 24, 73])

divide(x,y)
    

## Exercise 3 :  max_info() with NumPy

In [11]:
import numpy as np

def max_info(numbers):
    numbers=np.array(numbers)
    return numbers.max(),numbers.argmax()

numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

max_info(numbers)
    


(83, 2)