<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [ ]:
#Python Lists
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]


In [1]:
#Numpy Arrays
import numpy as np
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])


In [ ]:
#Dictionary
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

### 1.2 Accessing data from a list (or array)

In [ ]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

print(py_real_names[0])

### 1.3 Accessing data from a dictionary

In [8]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }
print(superhero_info["Natasha Romanoff"])

superhero_info.keys()
superhero_info.values()


Black Widow


dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [ ]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]


## 2 Lists vs. Arrays

### 2.1 Size

In [10]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array
len(py_list_2d)

10

In [10]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array
len(np_array_2d)

10

In [11]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array
np_array_2d.shape

(10, 2)

### 2.2 Arrays are fussy about type

In [12]:
py_list = [1, 1.5, 'A']
np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [ ]:
py_list + 10        # Won't work!


In [ ]:
np_array + 10

### 2.4 Adding another list

In [13]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

py_list_1 + py_list_2


[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [14]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [16]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)  

py_list*2


array([ 2,  4,  6,  8, 10])

In [17]:
np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [19]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [20]:
np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [21]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)      

py_list == 3     # Works, but what IS the question?

False

In [ ]:
py_list > 3      # Won't work!

In [22]:
np_array == 3  

array([False, False,  True, False, False])

In [ ]:
np_array > 3  

### 2.8 Mathematics

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [23]:
sum(py_list)     # sum() is a base Python function

15

In [24]:
max(py_list)     # max() is a base Python function

5

In [25]:
min(py_list)     # min() is a base Python function

1

In [26]:
py_list.sum()   # Won't work!
                # py list does not support sum 

AttributeError: 'list' object has no attribute 'sum'

In [ ]:
np_array.sum()

In [ ]:
np_array.mean()

In [ ]:
np_array.max()

In [ ]:
np_array.min()

## Exercise 1 :  Total recall?

1. 
- *Both can undergo len() to show size.* 
- Both stores data in sequence starting with 0

2. 
- *Adding a number does not work for python list* while it works for np arrays.
- Adding another list for python list corporates all individual objects into one list while for ny array it adds objects with the same sequence number to generate a new array with the same size as the original one.

3. Dictionary pairs a key with a value.


## Exercise 2 :  Index me

In [1]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])                     # Prints 'a1'
print(py_list[2])                     # Prints 'c3'
print(py_list[4])                     # Prints 'e5'
print(py_list[6])                     # Prints 'g7'
print(py_list[8])                     # Prints 'i9'

a1
c3
e5
g7
i9


In [9]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
                 
print(py_list[::2])                    

['a1', 'c3', 'e5', 'g7', 'i9']


## Exercise 3 :  Capitalise Heros

In [5]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper() 

print(superhero_info)

{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [1]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  
import numpy as np
np_array=np.array(numbers)

(np_array==1).sum()

9